USE WORLD;
CREATE TABLE STU(NO INT(5) PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20), MARKS INT(5));
ALTER TABLE STU AUTO_INCREMENT=100;
INSERT INTO STU(NAME,MARKS)VALUES ('A',60);
INSERT INTO STU(NAME,MARKS)VALUES ('B',55);
INSERT INTO STU(NAME,MARKS)VALUES ('C',66);
DELETE FROM STU WHERE NO=102;
SELECT * FROM STU;