Use world;
DESCRIBE COUNTRY;
SELECT * FROM COUNTRY;

SELECT AVG(GNP) FROM COUNTRY;
SELECT SUM(GNP) FROM COUNTRY;
SELECT MAX(GNP) FROM COUNTRY;
SELECT MIN(GNP) FROM COUNTRY;
SELECT COUNT(*) FROM COUNTRY;