Use mydb;
#create table
CREATE TABLE `STUDENTS`(ROLLNUMBER INT(5),NAME VARCHAR(19),MARKS INT(3));

#structure of table
DESCRIBE `STUDENTS`;

#insert data and get data from table
INSERT INTO `STUDENTS` VALUES(101,'RUSHI',80);
INSERT INTO `STUDENTS` VALUES(102,'USHA',50);
INSERT INTO `STUDENTS` VALUES(103,'RAVI',30);
INSERT INTO `STUDENTS` VALUES(104,'ASHI',90);
INSERT INTO `STUDENTS` (NAME,ROLLNUMBER,MARKS) VALUES('JANU',105,52);
INSERT INTO `STUDENTS` VALUES(106,'ULE',NULL);

#get data from table 
SELECT * FROM STUDENTS;

#get data from rows
SELECT * FROM STUDENTS;
SELECT ROLLNUMBER,NAME,MARKS FROM STUDENTS;

#use WHERE filter rows using condition
SELECT * FROM `STUDENTS` WHERE MARKS<50;
SELECT * FROM `STUDENTS` WHERE ROLLNUMBER=102;
SELECT DISTINCT * FROM `STUDENTS`;                               #NO DUPLICATES
SELECT DISTINCT NAME FROM `STUDENTS`;                             # NO DUPLICATE FROM COLUMN NAME
SELECT * FROM `STUDENTS` WHERE MARKS is NULL;
