#DDL-create,alter,drop,truncate,rename
USE mydb;
#1.create
CREATE TABLE STUDENT (ID INT(4), NAME VARCHAR(25));
DESCRIBE STUDENT;
INSERT INTO `STUDENT` VALUES(51,'RAJU');
INSERT INTO `STUDENT` VALUES(52,'SAVI');
INSERT INTO `STUDENT` VALUES(53,'PRAJU');
INSERT INTO `STUDENT` VALUES(54,'AJAY');

COMMIT;

SELECT * FROM `STUDENT`;

#2.alter:add,drop,modify,rename
#i.add
ALTER TABLE `STUDENT` ADD(GRADE VARCHAR(2));
ALTER TABLE `STUDENT` ADD(YAER INT(4));

#ii.drop
ALTER TABLE `STUDENT` DROP COLUMN YAER;

#iii.modify
ALTER TABLE `STUDENT` MODIFY COLUMN NAME VARCHAR(20);                               #modify the varchar size
DESCRIBE STUDENT;

#iv.rename
ALTER TABLE `STUDENT` RENAME COLUMN NAME TO FIRSTNAME;

#3.truncate
INSERT INTO `STUDENTS` VALUES(101,'RUSHI',80,'A');
INSERT INTO `STUDENTS` VALUES(102,'USHA',50,'A+');
INSERT INTO `STUDENTS` VALUES(103,'RAVI',30,'B');

TRUNCATE TABLE `STUDENTS`;
SELECT * FROM STUDENTS;

#4.drop
DROP TABLE `STUDENTS`;

#5.rename
USE testing;
RENAME TABLE course1 TO Course;
RENAME TABLE Course TO Course1;
