USE mydb;
CREATE TABLE TOYS(NUM INT(3) NOT NULL,TYPE VARCHAR(200),PRICE INT(4));

#1.not null
#INSERT INTO TOYS VALUES('NULL','RINGING',200);                    #ERROR AS WE USED ERROR
SELECT * FROM TOYS;
DROP TABLE TOYS;

#2.unique
CREATE TABLE TOYS(NUM INT(3) NOT NULL,TYPE VARCHAR(200) UNIQUE,PRICE INT(4));
INSERT INTO TOYS VALUES(1,'RINGING',200);                 #RIGING IS DUPLICATE

#3.primary key
CREATE TABLE TOYS(NUM INT(3) PRIMARY KEY ,TYPE VARCHAR(200) UNIQUE,PRICE INT(4));
INSERT INTO TOYS VALUES(1,'RINGING',200);                 #1 is primary key so no duplicate

#4.foreign key
CREATE TABLE SCHOOL (NO INT(3),NAME VARCHAR(15),MARKS INT(3), PRIMARY KEY(NO));
INSERT INTO SCHOOL VALUES(100,'ARUN',90);
INSERT INTO SCHOOL VALUES(101,'AMANN',78);
INSERT INTO SCHOOL VALUES(102,'ARJUN',54);
SELECT * FROM SCHOOL;

CREATE TABLE LIBRARY (NO INT(3),FOREIGN KEY(NO) REFERENCES SCHOOL(NO), BOOK VARCHAR(10));
INSERT INTO LIBRARY VALUES (102,'JAVA');
INSERT INTO LIBRARY VALUES (108,'SSCI');
INSERT INTO LIBRARY VALUES ('NULL','JIRA');
#SELECT * FROM LIBRARY;          #108,109 NOT INSERTED AS THIS NO IS NOT IN SCHOLLL TABLE
DROP TABLE LIBRARY

#on delete cascade
#CREATE TABLE LIBRARY (NO INT(3),FOREIGN KEY(NO) REFERENCES SCHOOL(NO) on delete cascade, BOOK VARCHAR(10));
#INSERT INTO LIBRARY VALUES (102,'JAVA');
#INSERT INTO LIBRARY VALUES ('NULL','JIRA');

#5.check
CREATE TABLE STUDENTS(NO INT(5),NAME VARCHAR(15),MARKS INT(5) CHECK(MARKS BETWEEN 50 AND 100)); 
INSERT INTO STUDENTS VALUES(101,'CHIRAG',60);
INSERT INTO STUDENTS VALUES(102,'RIYA',48);             #ERROR AS MARKS IS LESS THAN 50
INSERT INTO STUDENTS VALUES(103,'SUMIT',88);

CREATE TABLE CITY(NAME VARCHAR(15) CHECK(NAME IN('HYDRABAD','DELHI','CHENNAI','MUMBAI')),
COUNTRY VARCHAR(10),PIN INT(8));
INSERT INTO CITY VALUES('HYDRABAD','INDIA',412536);
INSERT INTO CITY VALUES('PUNE','INDIA',456536);           #ERROR AS PUNE IS NOT IN CONSTRAINTS
INSERT INTO CITY VALUES('MUMBAI','INDIA',462536);
SELECT * FROM CITY;

#6.default
CREATE TABLE ORDERS(ID INT(5),ORDERNUMBER INT(5),ORDERDATE datetime DEFAULT NOW());
INSERT INTO ORDERS (ID,ORDERNUMBER) VALUES(101,2456);
INSERT INTO ORDERS (ID,ORDERNUMBER) VALUES(102,5789);
INSERT INTO ORDERS (ID,ORDERNUMBER) VALUES(10,8156);
SELECT * FROM ORDERS;