USE mydb;
CREATE TABLE TOYS(NUM INT(3) NOT NULL,TYPE VARCHAR(200),PRICE INT(4));

#not null
#INSERT INTO TOYS VALUES('NULL','RINGING',200);                    #ERROR AS WE USED ERROR
SELECT * FROM TOYS;
DROP TABLE TOYS;

#unique
CREATE TABLE TOYS(NUM INT(3) NOT NULL,TYPE VARCHAR(200) UNIQUE,PRICE INT(4));
INSERT INTO TOYS VALUES(1,'RINGING',200);                 #RIGING IS DUPLICATE

#primary key
CREATE TABLE TOYS(NUM INT(3) PRIMARY KEY ,TYPE VARCHAR(200) UNIQUE,PRICE INT(4));
INSERT INTO TOYS VALUES(1,'RINGING',200);                 #1 is primary key so no duplicate

#foreign key
CREATE TABLE SCHOOL (NO INT(3),NAME VARCHAR(15),MARKS INT(3), PRIMARY KEY(NO));
INSERT INTO SCHOOL VALUES(100,'ARUN',90);
INSERT INTO SCHOOL VALUES(101,'AMANN',78);
INSERT INTO SCHOOL VALUES(102,'ARJUN',54);
SELECT * FROM SCHOOL;

CREATE TABLE LIBRARY (NO INT(3),FOREIGN KEY(NO) REFERENCES SCHOOL(NO), BOOK VARCHAR(10));
INSERT INTO LIBRARY VALUES (102,'JAVA');
INSERT INTO LIBRARY VALUES (108,'SSCI');
INSERT INTO LIBRARY VALUES ('NULL','JIRA');
#SELECT * FROM LIBRARY;          #108,109 NOT INSERTED AS THIS NO IS NOT IN SCHOLLL TABLE
DROP TABLE LIBRARY

#on delete cascade
CREATE TABLE LIBRARY (NO INT(3),FOREIGN KEY(NO) REFERENCES SCHOOL(NO) on delete cascade, BOOK VARCHAR(10));
INSERT INTO LIBRARY VALUES (102,'JAVA');
INSERT INTO LIBRARY VALUES (101,'SSCI');
INSERT INTO LIBRARY VALUES ('NULL','JIRA');
delete from school where NO=101;                   #we can now remove from parent due on delete cascade