USE TESTING;
SELECT * FROM EMPLOYE;

#group by
SELECT ID ,SUM(SALARY) FROM EMPLOYE GROUP BY ID;

#having
SELECT ID ,SUM(SALARY) FROM EMPLOYE GROUP BY ID HAVING SUM(SALARY)>20000;

#combine group and where
SELECT ID ,SUM(SALARY) FROM EMPLOYE WHERE ID<>50000 GROUP BY ID HAVING SUM(SALARY)>10000;

#order by
SELECT * FROM EMPLOYE ORDER BY SALARY;