USE mydb;
CREATE TABLE `EMPLOYEES`(ID INT(3),NAME VARCHAR(10),SALARY INT(5));
CREATE TABLE `STUD`(ROLL INT(2),NAME VARCHAR(10),MARKS INT(3));
INSERT INTO `EMPLOYEES` VALUES(101,'USHA',50000);
INSERT INTO `EMPLOYEES` VALUES(102,'ANAYE',25000);
INSERT INTO `EMPLOYEES` VALUES(103,'RUSHI',30000);
INSERT INTO `EMPLOYEES` VALUES(104,'UMESH',53000);
COMMIT;
INSERT INTO `STUD` VALUES(101,'ASHU',225);
INSERT INTO `STUD` VALUES(200,'SUMIT',285);
INSERT INTO `STUD` VALUES(103,'AJAY',325);
INSERT INTO `STUD` VALUES(114,'RAVI',385);
SELECT * FROM `EMPLOYEES`;
SELECT * FROM `STUD`;
#union
SELECT ID FROM EMPLOYEES UNION SELECT ROLL FROM STUD;

#union all
SELECT ID FROM EMPLOYEES UNION ALL SELECT ROLL FROM STUD;